config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :job, only: [:create]

  root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @current_host = Hostname.name
    @results = Result.order("created_at DESC").limit(10)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # POST /jobs
  def create
    enqueued_by_host = Hostname.name
    HostnameJob.perform_later(enqueued_by_host)
    redirect_to(:root)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/dashboard/index.html.haml
.container
  .row
    .col-md-8
      %h1
        == Host: #{@current_host}
    .col-md-4
      = link_to("Enqueue Job", jobs_path, class: "btn btn-primary",  method: "POST")
  .row
    .col-md-12
      %table.table.table-sm.table-bordered.table-hover
        %thead.thead-default
          %tr
            %th
              Enqueued by
            %th
              Run by
            %th
              Run at
        %tbody
          = render(@results)

app/views/layouts/_footer.html.haml
%footer

app/views/layouts/_head.html.haml
%meta{"http-equiv" => "X-UA-Compatible", content: "IE=edge,chrome=1"}
%meta{charset: "utf-8" }
%meta{name: "viewport", content: "width=device-width"}

%link{rel: 'icon', href: '/favicon.ico', type: 'image/x-icon'}
%link{rel: 'shortcut icon', href: '/favicon.ico', type: 'image/x-icon'}
%link{rel: 'apple-touch-icon', href: '/favicon.ico', type: 'image/x-icon'}

%title
  Rails Docker Demo

= csrf_meta_tags
= action_cable_meta_tag

= stylesheet_link_tag("application", media: "all", "data-turbolinks-track" => true)
= javascript_include_tag("application", "data-turbolinks-track" => true)

app/views/layouts/_header.html.haml
%nav.navbar.navbar-light.bg-faded
  = link_to("Rails Docker Demo", "#", class: "navbar-brand")

app/views/layouts/application.html.haml
!!!
%html
  = render(partial: "layouts/head")
  %body
    = render(partial: "layouts/header")
    .container
      .row
        = yield
    = render(partial: "layouts/footer")

app/views/results/_result.html.haml
%tr{ class: ("table-success" if result.enqueued_by_host == @current_host) }
  %td
    = result.enqueued_by_host
  %td
    = result.run_on_host
  %td
    = result.created_at